services:
  db:
    image: postgres:16-alpine
    container_name: openlaunch-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openlaunch
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: openlaunch-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker-data/redis:/data
